apiVersion: v1
kind: Service
metadata:
  name: dealership
  namespace: sn-labs-othmanezizip  # Ensure this matches your namespace
spec:
  selector:
    run: dealership  # This must match the labels in your deployment
  type: LoadBalancer  # Change to ClusterIP if you want internal access only
  ports:
    - protocol: TCP
      port: 8000  # External Port
      targetPort: 8000  # Port inside the container
