name: 'Lint Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files (Dummy Test)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Create Dummy Python File
        run: |
          echo "def hello():" > dummy.py
          echo "    print('Hello, world!')" >> dummy.py
          cat dummy.py  # Display the file for debugging

      - name: Install Python Linter
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8 on Dummy Python File
        run: |
          flake8 dummy.py
          echo "Python lint test passed"

  lint_js:
    name: Lint JavaScript Files (Dummy Test)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Create Dummy JavaScript File
        run: |
          echo "function hello() { console.log('Hello, world!'); }" > dummy.js
          cat dummy.js  # Display the file for debugging

      - name: Install JSHint
        run: npm install jshint --global

      - name: Run JSHint on Dummy JavaScript File
        run: |
          jshint dummy.js
          echo "JavaScript lint test passed"
