name: 'Lint Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      
      - name: Print working directory
        run: pwd
      
      - name: Run Python Linter
        run: |
          # Lint all Python files but exclude third-party and generated directories
          flake8 . --exclude=server/djangoenv,server/djangoproj,frontend/build
          echo "Linted all the Python files successfully"
          
  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      
      - name: Install JSHint
        run: npm install jshint --global
      
      - name: Run JavaScript Linter
        run: |
          # Only lint JavaScript source files (adjust the path as needed)
          find ./frontend/src -name "*.js" -exec jshint {} +
          echo "Linted all the JS files successfully"
